### CREATE NEW USER
POST http://localhost:8888/users
Content-Type: application/json

{
  "username": "testuser4",
  "email": "test4@test.test"
}

### GET ALL USERS
GET http://localhost:8888/users

### UPDATE USER
PUT http://localhost:8888/users/1
Content-Type: application/json

{
  "username": "damien"
}

### DELETE USER
DELETE http://localhost:8888/users/0


